version: '3.8'

services:
  altura-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: altura-site
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    restart: always
